name: secret-scanning-review-action
author: felickz
description: 'Increase the visibility of Secret Scanning alerts as part of pull request collaboration'
#inputs:
#  FailOnAlert:
#    description: A boolean to raise workflow/annotation error(instead of warning) if alert is detected.
#    required: false
#  FailOnAlertExcludeClosed:
#    description: A boolean to exclude an alert from FailOnAlert if it is marked as closed (state: 'resolved').
#    required: false
#NodeJS entry point for PWSH action
runs:
  using: node12
  main: _init/index.js
branding:
  icon: "lock"
  color: "gray-dark"
